version: "3"

services:
  db:
    image: postgres:15.2
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "ah_t_data:/var/lib/postgresql/data/"
    env_file: .env
    networks:
      - app-network
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - app-network
volumes:
  ah_t_data:


networks:
  app-network:
    driver: bridge
